In [1]:
import numpy as np
import torch

In [2]:
torch.cuda.is_available()

True

In [7]:
test_list = [3,5]
results = np.zeros((len(test_list),10000))
for i,seq in enumerate(test_list):
    results[i,seq] = 1
print(results[:,:10])

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [6]:
x = torch.empty(2,2,3)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [8]:
x = torch.rand(2,2)
x

tensor([[0.9716, 0.7362],
        [0.4634, 0.5269]])

In [9]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [11]:
x = torch.ones(2,2)
print(x.dtype)
x

torch.float32


tensor([[1., 1.],
        [1., 1.]])

In [14]:
x = torch.ones(2,2,dtype=torch.int)
print(x.dtype)
print(x.size())
x


torch.int32
torch.Size([2, 2])


tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [15]:
x = torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
# z = torch.add(x,y) # same thing
print(z)

tensor([[0.4423, 0.8018],
        [0.4140, 0.6367]])
tensor([[0.1202, 0.7941],
        [0.3590, 0.2611]])
tensor([[0.5625, 1.5959],
        [0.7731, 0.8978]])


In [20]:
y.add_(x)
print(y)

tensor([[0.5625, 1.5959],
        [0.7731, 0.8978]])


In [23]:
# basic operations
x = torch.rand(5,3)
print(x)
print(x[1,1])
print(x[1,1].item())

tensor([[0.2860, 0.6924, 0.8349],
        [0.0022, 0.5082, 0.4735],
        [0.6729, 0.2206, 0.5432],
        [0.4328, 0.4804, 0.6429],
        [0.6591, 0.4975, 0.2792]])
tensor(0.5082)
0.5081883668899536


In [27]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
z = x.view(2,8) # -1,8 also works
print(y)
print(z)

tensor([[0.2372, 0.5054, 0.5252, 0.7590],
        [0.8056, 0.5363, 0.7044, 0.8650],
        [0.6220, 0.4578, 0.1259, 0.5947],
        [0.8848, 0.0391, 0.6409, 0.6885]])
tensor([0.2372, 0.5054, 0.5252, 0.7590, 0.8056, 0.5363, 0.7044, 0.8650, 0.6220,
        0.4578, 0.1259, 0.5947, 0.8848, 0.0391, 0.6409, 0.6885])
tensor([[0.2372, 0.5054, 0.5252, 0.7590, 0.8056, 0.5363, 0.7044, 0.8650],
        [0.6220, 0.4578, 0.1259, 0.5947, 0.8848, 0.0391, 0.6409, 0.6885]])


In [30]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [33]:
# if we use cpu, a and b will share the same memory location, 
# but when using gpu, they are in different locations. 
print(a + 1) 
print(b)

tensor([2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1.]


In [34]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
b.numpy()

array([1., 1., 1., 1., 1.])

In [37]:
x = torch.ones(5, requires_grad=True) # calculate the gradients
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [15]:
# f = w * x

# f = 2 * x

X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# model prediction
def forward(x):
    return w * x

# loss = MSE
def loss(y,y_predicted):
    return ((y_predicted - y)**2).mean()

# gradient
# MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N 2x (w*x -y)

def gradient(x,y,y_predicted):
    return np.dot(2*x,y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # prediction = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y,y_pred)

    # gradients
    dw = gradient(X,Y,y_pred)

    #update weights
    w -= learning_rate * dw

    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')


print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 3: w = 1.872, loss = 0.76800019
epoch 5: w = 1.980, loss = 0.01966083
epoch 7: w = 1.997, loss = 0.00050332
epoch 9: w = 1.999, loss = 0.00001288
epoch 11: w = 2.000, loss = 0.00000033
epoch 13: w = 2.000, loss = 0.00000001
epoch 15: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [18]:
import torch
# f = w * x

# f = 2 * x

X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# model prediction
def forward(x):
    return w * x

# loss = MSE
def loss(y,y_predicted):
    return ((y_predicted - y)**2).mean()


print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # prediction = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y,y_pred)

    # gradients = backward pass
    l.backward() # dl/dw
    with torch.no_grad():
        #update weights
        w -= learning_rate * w.grad

    # zero gradients
    w.grad.zero_()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')


print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [30]:
# 1) Design model (input, output size, forward pass)
# 2) Construct loss and optimizer
# 3) Training loop
# - forward pass: compute prediction
# - backward pass: gradients
# - update our weights
import torch
import torch.nn as nn

import torch
# f = w * x

# f = 2 * x

X = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32).unsqueeze(1)

X_test = torch.tensor([5],dtype=torch.float32)

# model prediction
n_samples, n_features = X.shape
print(n_samples, n_features)

input_size = n_features
output_size = n_features



class LinearModel(nn.Module):

    def __init__(self,input_dim,output_dim):
        super(LinearModel,self).__init__()
        #define layers
        self.lin = nn.Linear(input_dim,output_dim)
    
    def forward(self,x):
        return self.lin(x)

model = nn.Linear(input_size, output_size) 

model = LinearModel(input_size, output_size) # same thing

print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

# loss = MSE
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)


# Training
learning_rate = 0.1
n_iters = 100

for epoch in range(n_iters):
    # prediction = forward pass
    y_pred = model(X)

    # loss
    l = loss(Y,y_pred)

    # gradients = backward pass
    l.backward() # dl/dw
    #update weights
    optimizer.step()
     
    # zero gradients
    optimizer.zero_grad()

    if epoch % 10 == 0:
        [w, b] = model.parameters()
        print(f'epoch {epoch+1}: w = {w[0][0].item():.3f}, loss = {l:.8f}')


print(f'Prediction after training: f(5) = {model(X_test).item():.3f}') 

4 1
Prediction before training: f(5) = 2.701
epoch 1: w = 2.530, loss = 14.60078430
epoch 11: w = 1.791, loss = 0.08225676
epoch 21: w = 1.834, loss = 0.04216808
epoch 31: w = 1.878, loss = 0.02295874
epoch 41: w = 1.910, loss = 0.01250054
epoch 51: w = 1.933, loss = 0.00680627
epoch 61: w = 1.951, loss = 0.00370587
epoch 71: w = 1.964, loss = 0.00201776
epoch 81: w = 1.973, loss = 0.00109863
epoch 91: w = 1.980, loss = 0.00059817
Prediction after training: f(5) = 9.969


In [20]:
torch.tensor([1,2,3,4]).unsqueeze(1)

tensor([[1],
        [2],
        [3],
        [4]])

In [21]:
torch.tensor([1,2,3,4]).view(-1,1)

tensor([[1],
        [2],
        [3],
        [4]])

![alt text](image.png)

![alt text](image-1.png)