In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"np_array: {np_array},\n x_np:{x_np}")

np_array: [[1 2]
 [3 4]],
 x_np:tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [15]:
np_test = torch.from_numpy((np.array(np.arange(10)).reshape(2,5)))
np_test.flatten()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [18]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6961, 0.8659],
        [0.4931, 0.4474]]) 



In [17]:
x_data.view(-1)

tensor([1, 2, 3, 4])

In [19]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} ")

Random Tensor: 
 tensor([[0.0970, 0.5097, 0.9500],
        [0.0872, 0.7314, 0.3079]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


In [23]:
torch.randint(10,(2,2))

tensor([[3, 7],
        [6, 3]])

In [24]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to(torch.cuda.current_device())
torch.cuda.current_device()

0

In [29]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
print(f"Tensor 已经转移到 {device} 上了")

Tensor 已经转移到 cuda 上了


In [30]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [31]:
t1 = torch.stack([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [33]:
# Arithmetic operations

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [34]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

矩阵乘法和逐元素乘法是两种不同的运算，在运算规则、形状要求、应用场景等方面都存在明显区别，下面为你详细介绍：

### 运算规则
- **矩阵乘法**：遵循线性代数中的矩阵乘法规则。若有两个矩阵 $\mathbf{A}$ 和 $\mathbf{B}$，设 $\mathbf{A}$ 是 $m \times n$ 的矩阵，$\mathbf{B}$ 是 $n \times p$ 的矩阵，那么它们的乘积 $\mathbf{C} = \mathbf{A} \mathbf{B}$ 是一个 $m \times p$ 的矩阵。其中，$\mathbf{C}$ 中第 $i$ 行第 $j$ 列的元素 $c_{ij}$ 等于 $\mathbf{A}$ 的第 $i$ 行与 $\mathbf{B}$ 的第 $j$ 列对应元素乘积之和，用公式表示为：
\[ c_{ij} = \sum_{k = 1}^{n} a_{ik}b_{kj} \]
例如：
\[
\mathbf{A} = 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}, 
\mathbf{B} = 
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
\]
\[
\mathbf{A} \mathbf{B} = 
\begin{bmatrix}
1\times5 + 2\times7 & 1\times6 + 2\times8 \\
3\times5 + 4\times7 & 3\times6 + 4\times8
\end{bmatrix} = 
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
\]
- **逐元素乘法**：也称为哈达玛积（Hadamard product），要求参与运算的两个矩阵形状相同。对于形状相同的矩阵 $\mathbf{A}$ 和 $\mathbf{B}$，它们的逐元素乘积 $\mathbf{C} = \mathbf{A} \odot \mathbf{B}$ 也是一个与它们形状相同的矩阵，其中 $\mathbf{C}$ 中第 $i$ 行第 $j$ 列的元素 $c_{ij}$ 等于 $\mathbf{A}$ 中第 $i$ 行第 $j$ 列的元素 $a_{ij}$ 与 $\mathbf{B}$ 中第 $i$ 行第 $j$ 列的元素 $b_{ij}$ 直接相乘，即 $c_{ij} = a_{ij} \times b_{ij}$。
例如：
\[
\mathbf{A} = 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}, 
\mathbf{B} = 
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
\]
\[
\mathbf{A} \odot \mathbf{B} = 
\begin{bmatrix}
1\times5 & 2\times6 \\
3\times7 & 4\times8
\end{bmatrix} = 
\begin{bmatrix}
5 & 12 \\
21 & 32
\end{bmatrix}
\]

### 形状要求
- **矩阵乘法**：前一个矩阵的列数必须等于后一个矩阵的行数。例如，一个 $3 \times 2$ 的矩阵可以与一个 $2 \times 4$ 的矩阵相乘，得到一个 $3 \times 4$ 的矩阵，但不能与一个 $3 \times 4$ 的矩阵相乘。
- **逐元素乘法**：两个矩阵的形状必须完全相同。例如，两个 $3 \times 2$ 的矩阵可以进行逐元素乘法，而一个 $3 \times 2$ 的矩阵和一个 $2 \times 3$ 的矩阵不能进行逐元素乘法。

### 应用场景
- **矩阵乘法**：
    - **线性变换**：在计算机图形学中，矩阵乘法可用于实现图形的旋转、缩放、平移等线性变换。
    - **神经网络**：在神经网络的全连接层中，输入层与隐藏层、隐藏层与输出层之间的连接通常通过矩阵乘法来实现。
    - **数据降维**：主成分分析（PCA）等数据降维方法中也会用到矩阵乘法。
- **逐元素乘法**：
    - **激活函数**：在神经网络中，激活函数常常会对输入的每个元素进行逐元素操作，例如 ReLU 函数就是对输入的每个元素取最大值（0 和该元素本身）。
    - **损失函数**：在一些损失函数中，会对预测值和真实值进行逐元素的加权操作，这时就会用到逐元素乘法。
    - **特征缩放**：在数据预处理中，有时会对特征矩阵的每个元素进行缩放，也会用到逐元素乘法。

综上所述，矩阵乘法和逐元素乘法是两种不同的运算，在实际应用中需要根据具体需求选择合适的运算方式。 

In [35]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [36]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [37]:
t =torch.ones(5)
n = t.numpy()
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [39]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
